version:                   "3"
services:
  nginx:
    build:
        context:           .
        dockerfile:        Dockerfile-nginx.dockerfile
    volumes:
      - ./html:/usr/share/nginx/html
      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      # - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configs/example.com.conf:/etc/nginx/sites-enabled/example.com.conf
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    depends_on:
      - "php"
      - "db"
  php:
    build:
      context:             .
      dockerfile:          Dockerfile-php.dockerfile
    volumes:
      - ./html:/var/www/html
      - ./configs/php.ini:/usr/local/etc/php/php.ini
      - ./configs/supervisor:/etc/supervisor/conf.d
      - ./logs/worker.log:/logs/worker.log
    depends_on:
      - "db"
  db:
    image:                 mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE:      shop
      MYSQL_USER:          ruzy
      MYSQL_PASSWORD:      dd360870
  adminer:
    image:                 adminer
    ports:
      - 8080:8080
  redis:
    image:                 redis:alpine
    volumes:
      - ./data/redis:/data
